### ISSUE TITLE
`minLength` and `maxLength` definitions for `string` type can generate validators

### ISSUE THREAD

**Issue by cobusc** [DavidOberholzer/SwaggerReactAdminGenerator#2]
Currently a definition like this
```
      account_id:
        type: string
        minLength: 32
        maxLength: 256
```
generates `<TextInput source="account_id" />` in the `Create`and `Edit` views.
This should ideally be:
```
import {
   ...
    minLength,
    maxLength
} from 'react-admin';

const lengthValidators = [minLength(32), maxLength(256)]
...
<TextInput source="account_id" validate={lengthValidators} />
```
Link to the docs: https://github.com/marmelab/react-admin/blob/master/docs/CreateEdit.md#built-in-field-validators
